name: ai_pdf_reader
description: A Flutter package for PDF reading, text extraction, TTS audio playback, offline summary generation, and reading progress tracking.
version: 0.0.5

homepage: https://github.com/NafimAhmed/ai_pdf_reader_package
repository: https://github.com/NafimAhmed/ai_pdf_reader_package
issue_tracker: https://github.com/NafimAhmed/ai_pdf_reader_package/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.2.3
  flutter_tts: ^4.2.5
  syncfusion_flutter_pdf: 30.2.7
  syncfusion_flutter_pdfviewer: 30.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: